apiVersion: v1
kind: ServiceAccount
metadata:
  name: poduser
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: Role 
metadata: 
  namespace: default 
  name: pods-manager 
rules: 
- apiGroups: [""] 
  resources: ["pods", "pods/exec"] 
  verbs: ["*"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pods-manager-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: poduser
  apiGroup: ""
roleRef:
  kind: Role
  name: pods-manager
  apiGroup: ""
